### ISSUE TITLE
Smart Sync current or recursive folder sync

### ISSUE THREAD

**Issue by hakan-demirli** [PrinceOfPuppers/sync-dl#12]
Add a way to sync the current folder or all the folders in the current directory.

Possible implementations:
```
sync-dl sync -s ./
sync-dl sync -s --current-folder
sync-dl sync -s -cf
sync-dl sync -s -cwd
sync-dl sync -s --recursive
sync-dl sync -s -r
```

Possible use cases:
* Currently, the user has to type the playlist folder names manually to sync them. Typing becomes more tedious if the folder name is in a different typing system (Latin, Kanji, etc.).
* Since sync-dl does not offer a batch sync implementation. The user has to manually type all the playlist folder names, there may be hundreds of them.

**Comment by PrinceOfPuppers** [comment]
I can add this, I think I'll go with the `-r --recursive` flags which will check the specified folder and its subfolders for playlists. Never came across this in my own use as I only use 5 playlists for my music.

**Comment by PrinceOfPuppers** [comment]
new version is on pypi:
https://pypi.org/project/sync-dl/2.3.4/

`pip install -U sync-dl`
