### ISSUE TITLE
Thumbnail enable breaks unlisted playlists without ffmpeg

### ISSUE THREAD

**Issue by hakan-demirli** [PrinceOfPuppers/sync-dl#14]
`sync-dl 2.3.4`
This is a really weird bug. I don't really mind whether it is fixed or not. I just wanted to share it for others who may encounter it.

## Details
If ffmpeg is not installed and the thumbnails are enabled, sync-dl can't download unlisted playlists. But, it can download public playlists.
I have tried the same commands on a fresh Windows install but the result is the same. 
```
sync-dl config -T
sync-dl new <UNLISTED-PLAYLIST> my_playlist
Unable to Download Song at <LEGIT-VIDEO-URL>
Retrying...
```
It downloads successfully if I disable thumbnails.
It downloads successfully if I set the visibility to public.
It downloads successfully if I install ffmpeg.

I have no idea how an unlisted playlist requires ffmpeg but a public one doesn't.
I don't know if the bug is fixable since there is no mention of playlist visibility in the code. Maybe the reason is something from yt-dlp, youtube api or my home internet.

**Comment by PrinceOfPuppers** [comment]
Thanks for the details, glad to see you're still using the app.

My first guess is its something with `yt-dlp`, did you try updating `yt-dlp` to see if this issue persists? I'll do some testing on my end as well, if this is an issue with `yt-dlp` I'll raise the issue with them. In general I find all versions of `youtube-dl` behave strangely if you don't have ffmpeg installed (hence why the default config values for `sync-dl` are the way they are)

**Comment by hakan-demirli** [comment]
~~I have tried it with version `2022.5.18` and `2021.11.10`. Both have failed. I have also tried to download a huge playlist and observed the internet usage. sync-dl does really download the sounds. Sounds are being created in the tmp folder and then discarded.~~

There is no bug. It's my bad. I have added sync-dl to my personal flask dashboard which has its own virtual environment and terminal tab. I forgot that the packages are seperate from my regular terminal.
Everything is working as expected.

**Comment by PrinceOfPuppers** [comment]
Ah ok np, thanks for catching the error. Sounds like a pretty cool setup though ^^.

**Comment by hakan-demirli** [comment]
Thank you. I am planning to open-source it as soon as I finish code refactoring and documentation. Right now, it consists of hacks on top of hacks.

**Comment by PrinceOfPuppers** [comment]
nice, excited to see it.
