### ISSUE TITLE
Custom File Format and Embed Thumbnail

### ISSUE THREAD

**Issue by hakan-demirli** [PrinceOfPuppers/sync-dl#6]
Allow user to pass an `--audio-format` parameter to youtube-dl.
Allow user to activate `--embed-thumbnail` parameter of youtube-dl.

Sync-dl can take these parameters while creating the main folder.
```
sync-dl config -l my/local/music/folder --audio-format mp3 --embed-thumbnail
```

Or different options per playlist.
```
sync-dl new https://www.youtube.com/playlist?list=PL-lQgJ3eJ1HtLvM6xtxOY_1clTLov0qM3 sweetJams --audio-format mp3 --embed-thumbnail
```
**Possible use cases:**

- Scrolling through a music playlist consisting of hundreds of songs. Thumbnails allow users to scroll down comfortably and fast without reading song titles. 

- The audio format is just for compatibility.

**Comment by PrinceOfPuppers** [comment]
Both doable, ETA: next week.

Thumbnails:
I actually looked into this a while ago, there was some oddness with requiring atomic parsley involved that deterred me from it, but I can look into it again (I'm having the same issue with playlist length). I'll add it to the config and add a wrapper to toggle it on/off for convenience.

Audio format
That should be no issue, I did the somewhat hacky solution for m4a for another user, time to generalize that solution.

**Comment by hakan-demirli** [comment]
I have tried the [development branch](https://github.com/PrinceOfPuppers/sync-dl/tree/formats-and-thumbnails). And it is working perfectly.

**Comment by PrinceOfPuppers** [comment]
Still going to work on it some more, I've noticed a significant download speed reduction with it and I want to rectify that before release. 

Also want to do more testing to check for bugs

**Comment by PrinceOfPuppers** [comment]
new version is on pypi:
https://pypi.org/project/sync-dl/2.3.0/ 

`pip install -U sync-dl`
